twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        token_mapbox_gl: 'pk.eyJ1IjoiZi10dWZmIiwiYSI6ImNrbWI0dnQzdzE0ODIydnBoOW5uMGw4ZXUifQ.-7cgcpBp7TUjYuCspjT04w'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]